apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

prune: true

datasources:
  - name: VictoriaMetrics
    uid: victoriametrics
    type: prometheus
    access: proxy
    url: http://victoriametrics:8428
    isDefault: true
    editable: false
  - name: Prometheus (Local)
    uid: victoriametrics-local
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: false
