name: Renovate Auto Approve

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions: {}

jobs:
  auto-approve-renovate:
    name: Auto Approve Renovate
    uses: TimSchoenle/actions/.github/workflows/maintenance-auto-approve-renovate.yaml@cb32bfedbd3e69163f0627e005b005866503de28 # tag=workflows-maintenance-auto-approve-renovate-v1.4.4
    permissions:
      pull-requests: write # To approve PRs
    with:
      user_ids: '29139614,253958393' # Renovate, actions-maintenance-bot
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
