name: Renovate Auto Approve

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions: {}

jobs:
  auto-approve-renovate:
    name: Auto Approve Renovate
    uses: TimSchoenle/actions/.github/workflows/maintenance-auto-approve-renovate.yaml@f804c0a110a7961525b9ecfa42c328e75cd11d4a # tag=workflows-maintenance-auto-approve-renovate-v1.4.6
    permissions:
      pull-requests: write # To approve PRs
    with:
      user_ids: '29139614,253958393' # Renovate, actions-maintenance-bot
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
